{application,my_app,
             [{applications,[kernel,stdlib,elixir,logger,ex_aws,sweet_xml,
                             broadway_sqs,aws,jason,hackney,httpoison]},
              {description,"my_app"},
              {modules,['Elixir.MyApp','Elixir.MyApp.Application',
                        'Elixir.MyApp.MyBroadway']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.MyApp.Application',[]}}]}.
